version: '3.8'

services:
  # Example 1: Environment Variables Only (No config.json)
  torrentjanitor-simple:
    image: torrentjanitor:latest
    container_name: torrentjanitor-simple
    environment:
      # Connection settings via environment
      - QB_HOST=qbittorrent
      - QB_PORT=8080
      - QB_USERNAME=admin
      - QB_PASSWORD=adminadmin
      - TZ=UTC
      - PYTHONUNBUFFERED=1
      - WORK_DIR=/data
    volumes:
      # Only data directory, no config file
      - ./data:/data
    restart: unless-stopped

  # Example 2: Mixed Configuration (RECOMMENDED)
  torrentjanitor-mixed:
    image: torrentjanitor:latest
    container_name: torrentjanitor
    environment:
      # Connection via environment (flexible)
      - QB_HOST=qbittorrent
      - QB_PORT=8080
      - QB_USERNAME=${QB_USERNAME}
      - QB_PASSWORD=${QB_PASSWORD}
      - TZ=${TZ}
      - PYTHONUNBUFFERED=1
    volumes:
      # Config for rules, data for state
      - ./config.json:/config/config.json:ro
      - ./data:/data
    restart: unless-stopped

  # Example 3: With VPN (Gluetun)
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    # ... VPN configuration
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    # ... qBittorrent configuration
    
  torrentjanitor-vpn:
    image: torrentjanitor:latest
    container_name: torrentjanitor
    environment:
      # Use container name for VPN setup
      - QB_HOST=gluetun  # NOT localhost!
      - QB_PORT=8080
      - QB_USERNAME=admin
      - QB_PASSWORD=adminadmin
    volumes:
      - ./config.json:/config/config.json:ro
      - ./data:/data
    depends_on:
      - gluetun
      - qbittorrent
    restart: unless-stopped

  # Example 4: Multiple Instances
  torrentjanitor-main:
    image: torrentjanitor:latest
    container_name: torrentjanitor-main
    environment:
      - QB_HOST=qbittorrent-main
      - QB_PORT=8080
      - QB_USERNAME=admin
      - QB_PASSWORD=adminadmin
    volumes:
      - ./configs/main.json:/config/config.json:ro
      - ./data/main:/data
    restart: unless-stopped

  torrentjanitor-secondary:
    image: torrentjanitor:latest
    container_name: torrentjanitor-secondary
    environment:
      - QB_HOST=qbittorrent-secondary
      - QB_PORT=8085
      - QB_USERNAME=admin
      - QB_PASSWORD=adminadmin
    volumes:
      - ./configs/secondary.json:/config/config.json:ro
      - ./data/secondary:/data
    restart: unless-stopped