version: '3.8'

services:
  # Example 1: Basic setup with qBittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ./downloads:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  torrentjanitor:
    build: .
    # Or use image if published to Docker Hub
    # image: yourusername/torrentjanitor:latest
    container_name: torrentjanitor
    environment:
      - QB_HOST=qbittorrent
      - QB_PORT=8080
      - QB_USERNAME=admin
      - QB_PASSWORD=adminadmin
      - TZ=UTC
      - PYTHONUNBUFFERED=1
    volumes:
      - ./torrentjanitor/config:/config
      - ./torrentjanitor/data:/data
    depends_on:
      - qbittorrent
    restart: unless-stopped

---
# Example 2: With VPN (Gluetun)
version: '3.8'

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8080:8080"  # qBittorrent WebUI
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      # Add your VPN credentials here
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=Netherlands
    volumes:
      - ./gluetun:/gluetun
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ./downloads:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

  torrentjanitor:
    build: .
    container_name: torrentjanitor
    environment:
      - QB_HOST=gluetun  # Use VPN container for access
      - QB_PORT=8080
      - QB_USERNAME=${QB_USERNAME:-admin}
      - QB_PASSWORD=${QB_PASSWORD:-adminadmin}
      - TZ=UTC
      - PYTHONUNBUFFERED=1
    volumes:
      - ./torrentjanitor/config:/config
      - ./torrentjanitor/data:/data
    depends_on:
      - gluetun
      - qbittorrent
    restart: unless-stopped

---
# Example 3: Multiple instances with different configs
version: '3.8'

services:
  # Aggressive cleaning for public torrents
  torrentjanitor-public:
    build: .
    container_name: torrentjanitor-public
    environment:
      - QB_HOST=qbittorrent
      - QB_PORT=8080
      - QB_USERNAME=admin
      - QB_PASSWORD=adminadmin
    volumes:
      - ./configs/public-config.json:/config/config.json:ro
      - ./torrentjanitor/public-data:/data
    restart: unless-stopped

  # Conservative cleaning for private trackers
  torrentjanitor-private:
    build: .
    container_name: torrentjanitor-private
    environment:
      - QB_HOST=qbittorrent
      - QB_PORT=8080
      - QB_USERNAME=admin
      - QB_PASSWORD=adminadmin
    volumes:
      - ./configs/private-config.json:/config/config.json:ro
      - ./torrentjanitor/private-data:/data
    restart: unless-stopped